version: '2.14.0'

services:
  sentiment-analysis:
    image: 'shafreen/sentiment-api:0.0.1'
    ports:
      - '9099:9099'
    network_mode: "host"

  sentiment-analysis-secured:
    image: 'shafreen/sentiment-api-secured:0.0.1'
    ports:
      - '9098:9098'
    network_mode: "host"

  sts:
    image: 'shafreen/sts-service:0.0.1'
    ports:
      - '9445:9445'
    network_mode: "host"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    network_mode: "host"

  mysql:
    image: 'mysql:8-oracle'
    ports:
      - '3306:3306'
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=dummypassword
      - MYSQL_DATABASE=social_media_database
      - MYSQL_USER=social_media_user
      - MYSQL_PASSWORD=dummypassword
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - "./db-setup/init.sql:/docker-entrypoint-initdb.d/1.sql"
