version: '2.14.0'

services:
  social-media:
    image: 'wso2/social-media:0.0.1'
    ports:
      - '9090:9090'
    depends_on: 
      jaeger: 
          condition: service_started
      sentiment-analysis: 
          condition: service_started
      sts: 
          condition: service_started
      mysql: 
          condition: service_healthy
    network_mode: "host"

  slack-message-sender:
    image: 'wso2/slack-message-sender:0.0.1'
    depends_on: 
      jaeger: 
          condition: service_started
      nats: 
          condition: service_started
    network_mode: "host"

  sentiment-analysis:
    image: 'wso2/sentiment-api-secured:0.0.1'
    ports:
      - '9098:9098'
    depends_on: 
      - jaeger
    network_mode: "host"

  jaeger:
    image: 'jaegertracing/opentelemetry-all-in-one'
    ports:
      - '13133:13133'
      - '16686:16686'
      - '55680:55680'
    network_mode: "host"

  sts:
    image: 'wso2/sts-service:0.0.1'
    ports:
      - '9445:9445'
    network_mode: "host"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    network_mode: "host"

  mysql:
    image: 'mysql:8-oracle'
    ports:
      - '3306:3306'
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=dummypassword
      - MYSQL_DATABASE=social_media_database
      - MYSQL_USER=social_media_user
      - MYSQL_PASSWORD=dummypassword
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
    volumes:
      - "./db-setup/init.sql:/docker-entrypoint-initdb.d/1.sql"
