[container.image]
repository="shafreen"
name="sentiment-api-secured"
tag="0.0.1"

[[container.copy.files]]
sourceFile="./resources/private.key"
target="./resources/private.key"

[[container.copy.files]]
sourceFile="./resources/public.crt"
target="./resources/public.crt"
