moderate = true

database_user = "social_media_user"
database_password = "dummypassword"
host = "localhost"
port = 3306

[ballerina.observe]
tracingEnabled=true
tracingProvider="jaeger"

[ballerinax.jaeger]
samplerParam=1.0